name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
        - name: 🦑 Personal metrics
          uses: lowlighter/metrics@latest
          with:
            filename: github-metrics.svg
            token: ${{ secrets.METRICS_TOKEN }}
            committer_token: ${{ secrets.GITHUB_TOKEN }}
            repositories_forks: true
            plugin_lines: yes
            plugin_languages: yes
            plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c
            plugin_languages_details: bytes-size, percentage
            config_timezone: Asia/Jakarta
        - name: 🦑 Additonal metrics
          uses: lowlighter/metrics@latest
          with:
            filename: github-metrics-additional.svg
            token: ${{ secrets.METRICS_TOKEN }}
            committer_token: ${{ secrets.GITHUB_TOKEN }}
            plugin_habits: yes
            plugin_habits_from: 200
            plugin_habits_facts: yes
            plugin_habits_charts: yes
            config_timezone: Asia/Jakarta  
            

    
